package geo;
// Generated 10/11/2015 17:08:58 by Hibernate Tools 4.3.1.Final

/**
 * Instituts generated by hbm2java
 */
public class Instituts implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codi;
	private Poblacions poblacions;
	private String nom;
	private String adreca;
	private String numero;
	private Integer codpostal;

	public Instituts() {
	}

	public Instituts(String codi) {
		this.codi = codi;
	}

	public Instituts(String codi, Poblacions poblacions, String nom, String adreca, String numero, Integer codpostal) {
		this.codi = codi;
		this.poblacions = poblacions;
		this.nom = nom;
		this.adreca = adreca;
		this.numero = numero;
		this.codpostal = codpostal;
	}

	public String getCodi() {
		return this.codi;
	}

	public void setCodi(String codi) {
		this.codi = codi;
	}

	public Poblacions getPoblacions() {
		return this.poblacions;
	}

	public void setPoblacions(Poblacions poblacions) {
		this.poblacions = poblacions;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public String getAdreca() {
		return this.adreca;
	}

	public void setAdreca(String adreca) {
		this.adreca = adreca;
	}

	public String getNumero() {
		return this.numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public Integer getCodpostal() {
		return this.codpostal;
	}

	public void setCodpostal(Integer codpostal) {
		this.codpostal = codpostal;
	}

}
