package geo;
// Generated 10/11/2015 17:08:58 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Poblacions generated by hbm2java
 */
public class Poblacions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int codM;
	private Comarques comarques;
	private String nom;
	private Integer poblacio;
	private BigDecimal extensio;
	private Short altura;
	private String longitud;
	private String latitud;
	private Character llengua;
	private Set<Instituts> institutses = new HashSet<Instituts>(0);

	public Poblacions() {
	}

	public Poblacions(int codM, String nom) {
		this.codM = codM;
		this.nom = nom;
	}

	public Poblacions(int codM, Comarques comarques, String nom, Integer poblacio, BigDecimal extensio, Short altura,
			String longitud, String latitud, Character llengua, Set<Instituts> institutses) {
		this.codM = codM;
		this.comarques = comarques;
		this.nom = nom;
		this.poblacio = poblacio;
		this.extensio = extensio;
		this.altura = altura;
		this.longitud = longitud;
		this.latitud = latitud;
		this.llengua = llengua;
		this.institutses = institutses;
	}

	public int getCodM() {
		return this.codM;
	}

	public void setCodM(int codM) {
		this.codM = codM;
	}

	public Comarques getComarques() {
		return this.comarques;
	}

	public void setComarques(Comarques comarques) {
		this.comarques = comarques;
	}

	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	public Integer getPoblacio() {
		return this.poblacio;
	}

	public void setPoblacio(Integer poblacio) {
		this.poblacio = poblacio;
	}

	public BigDecimal getExtensio() {
		return this.extensio;
	}

	public void setExtensio(BigDecimal extensio) {
		this.extensio = extensio;
	}

	public Short getAltura() {
		return this.altura;
	}

	public void setAltura(Short altura) {
		this.altura = altura;
	}

	public String getLongitud() {
		return this.longitud;
	}

	public void setLongitud(String longitud) {
		this.longitud = longitud;
	}

	public String getLatitud() {
		return this.latitud;
	}

	public void setLatitud(String latitud) {
		this.latitud = latitud;
	}

	public Character getLlengua() {
		return this.llengua;
	}

	public void setLlengua(Character llengua) {
		this.llengua = llengua;
	}

	public Set<Instituts> getInstitutses() {
		return this.institutses;
	}

	public void setInstitutses(Set<Instituts> institutses) {
		this.institutses = institutses;
	}

}
