package dades;
// Generated 25/11/2015 18:19:51 by Hibernate Tools 4.3.1.Final

/**
 * PuntId generated by hbm2java
 */
public class PuntId implements java.io.Serializable {

	private int numR;
	private int numP;

	public PuntId() {
	}

	public PuntId(int numR, int numP) {
		this.numR = numR;
		this.numP = numP;
	}

	public int getNumR() {
		return this.numR;
	}

	public void setNumR(int numR) {
		this.numR = numR;
	}

	public int getNumP() {
		return this.numP;
	}

	public void setNumP(int numP) {
		this.numP = numP;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PuntId))
			return false;
		PuntId castOther = (PuntId) other;

		return (this.getNumR() == castOther.getNumR()) && (this.getNumP() == castOther.getNumP());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getNumR();
		result = 37 * result + this.getNumP();
		return result;
	}

}
