package dades;
// Generated 25/11/2015 18:19:51 by Hibernate Tools 4.3.1.Final

/**
 * Punt generated by hbm2java
 */
public class Punt implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private PuntId id;
	private Ruta ruta;
	private String nomP;
	private Float latitud;
	private Float longitud;

	public Punt() {
	}

	public Punt(PuntId id, Ruta ruta) {
		this.id = id;
		this.ruta = ruta;
	}

	public Punt(PuntId id, Ruta ruta, String nomP, Float latitud, Float longitud) {
		this.id = id;
		this.ruta = ruta;
		this.nomP = nomP;
		this.latitud = latitud;
		this.longitud = longitud;
	}

	public PuntId getId() {
		return this.id;
	}

	public void setId(PuntId id) {
		this.id = id;
	}

	public Ruta getRuta() {
		return this.ruta;
	}

	public void setRuta(Ruta ruta) {
		this.ruta = ruta;
	}

	public String getNomP() {
		return this.nomP;
	}

	public void setNomP(String nomP) {
		this.nomP = nomP;
	}

	public Float getLatitud() {
		return this.latitud;
	}

	public void setLatitud(Float latitud) {
		this.latitud = latitud;
	}

	public Float getLongitud() {
		return this.longitud;
	}

	public void setLongitud(Float longitud) {
		this.longitud = longitud;
	}

}
